MALE_NAMES = [
    "Allan", 
    "Bo", 
    "Charlie", 
    "Demetri", 
    "Eric", 
    "Freddy", 
    "George", 
    "Henry", 
    "Igor", 
    "Jerry", 
    "Kaleb", 
    "Larry", 
    "Manny", 
    "Nicholas", 
    "Obie", 
    "Peter", 
    "Quay", 
    "Rudy",
    "Steve",
    "Timmy",
    "Umar",
    "Victor",
    "Woody",
    "Xander",
    "Yannis",
    "Zasou"]

LAST_NAMES = [
    "Anderson",
    "Brown",
    "Carlyle",
    "Donaldson",
    "Willaims",
    "Roberts",
    "Wilson",
    "Jones",
    "Miller",
    "Murphy",
    "Davies",
    "Smith",
    "Rodriguez",
    "Lee",
    "Singh",
    "Gundersen",
    "White",
    "Larson",
    "Müller",
    "Meyer",
    "Wagner",
    "Weber",
    "Fischer",
    "Schneider",
    "Schmidt",
    "Johnson"]

COURSES = [
    ["Math A", "111", "John Watkins", 24, 0],
    ["Math B", "101", "Burt Johnson", 16, 0],
    ["English A", "505", "Jane Foster", 20, 0],
    ["English B", "501", "Tina Fey", 14, 0],
    ["Biology A", "331", "Liz Johnson", 22, 0],
    ["Biology B", "321", "John Henson", 14, 0],
    ["German A", "222", "Michael Schultze", 18, 0],
    ["German B", "202", "Henke Müller", 12, 0],
    ["Chemistry A", "305", "Reese Witherspoon", 22, 0],
    ["Chemistry B", "301", "Ben Wilson", 16, 0],
    ["French A", "409", "Lina Jenkins", 20, 0],
    ["French B", "404", "Sylvia Laurent", 14, 0],
    ["Spanish A", "440", "Jerry Larson", 20, 0],
    ["Spanish B", "432", "Don Heguin", 12, 0],
    
]

GRADES = [-3, 0, 2, 4, 7, 10, 12]


PIC_URLS_MALES = ["https://img.freepik.com/free-photo/front-view-male-student-dark-t-shirt-yellow-backpack-holding-files-books-smiling-light-blue-wall_140725-46715.jpg?w=2000",
                  "https://image.shutterstock.com/image-photo/portrait-smiling-young-college-student-260nw-1192615495.jpg",
                  "https://st.depositphotos.com/1199142/1784/i/600/depositphotos_17840989-stock-photo-young-happy-student-carrying-books.jpg",
                  "https://www.kindpng.com/picc/m/57-574905_black-college-student-png-transparent-png.png",
                  "https://media.istockphoto.com/photos/happy-smiling-student-with-his-notebook-and-backpack-picture-id452257843?k=20&m=452257843&s=612x612&w=0&h=CO5tQouEz8Gwo0t0A4AK3EGss0TDDFFB4oahJHqjRqs=",
                  "https://thumbs.dreamstime.com/b/photo-image-portrait-funny-attractive-cute-young-asian-student-white-shirt-smiling-pointing-forward-side-view-isolated-104697224.jpg"]


